bindings/rust/Cargo.toml, tools/compiler/Cargo.lock
See [here](https://github.com/nervosnetwork/faster-hex/pull/9) for related change.
=> Bump faster hex version

examples/ci-tests/src/main.rs, tools/codegen/src/generator/languages/rust/entity/mod.rs, tools/codegen/src/generator/languages/rust/getters.rs, tools/codegen/src/generator/languages/rust/reader/implementation.rs, tools/codegen/src/generator/languages/rust/reader/mod.rs
=> few minor improvements

bindings/rust/Cargo.toml, bindings/rust/src/bytes.rs, bindings/rust/src/error.rs, bindings/rust/src/io.rs, bindings/rust/src/lib.rs, bindings/rust/src/prelude.rs, bindings/rust/src/primitive.rs, examples/ci-tests/Cargo.toml, examples/ci-tests/Makefile, examples/ci-tests/src/lib.rs, tools/codegen/Cargo.toml, tools/codegen/src/generator/languages/rust/builder/definition.rs, tools/codegen/src/generator/languages/rust/builder/implementation.rs, tools/codegen/src/generator/languages/rust/builder/setters.rs, tools/codegen/src/generator/languages/rust/display.rs, tools/codegen/src/generator/languages/rust/entity/implementation.rs, tools/codegen/src/generator/languages/rust/entity/mod.rs, tools/codegen/src/generator/languages/rust/enumerator.rs, tools/codegen/src/generator/languages/rust/iterator.rs, tools/codegen/src/generator/languages/rust/reader/mod.rs, tools/compiler/Cargo.lock
At first, I try to do just few changes on #12, but after a lot of tests, I think there are lots of things could be remove or update in that PR, so I use the master branch as my base branch and implement it in another way.
The reasons why I didn't just approve that PR or just updated from that PR:
- The test for `no-std` in that PR (`examples/nostd-tests`) didn't work correctly.
Reason:
- `std` is the default feature for `molecule`.
- `codegen` is dependent on `molecule`.
- `build.rs` for `examples/nostd-tests` is dependent on `molecule`.
- Since rust had compiled the moleculewith `feature = "std"`, it will use the molecule with `feature = "std"`, even though we had written the `default-features = false` in `Cargo.toml`.
- So, at last, `examples/nostd-tests` is dependent on `molecule`with …
=> feat: rust support `#![no_std]`

examples/ci-tests/Makefile, tools/codegen/src/generator/languages/c/mod.rs
There is a bug:
- The api decorator for C functions is introduced by #8.
When we found there is no api decorator, we will set a default api decorator.
- If a decorator was defined as default at the beginning, then undef it at the end, since #9.
- **[BUG] But the macros which are used to test if the decorator is the default decorator have a same name  in different headers.**
So, the default decorator will be undef too early.
- I already wrote some tests, but I forgot to enable them in CI.
=> fix(codegen/c): name conflict for a kind of generated macros

README.md
The current JS implementation is not friendly for contract developers, which are our main audiences.
=> Remove link to the JS generator

README.md
These editors plugins can make the schema files more readable (especially when you have a lot of comments in your schema files).
=> docs: add links for several editors plugins

bindings/c/include/molecule_builder.h, bindings/c/include/molecule_reader.h, examples/ci-tests/Makefile, examples/ci-tests/c/test-build-default.c, tools/codegen/src/generator/languages/c/mod.rs
- All `include` should be put before call those two macros to avoid nested.
- It's a warning for ISO C++, and I update the implementation to make g++ be happy.
Still require the feature "C99 compound literals".
=> fix: fix comipile errors for c++

examples/ci-tests/Makefile
replace `TMPDIR` with `TARGET_TMP_DIR`, old one is in conflict with MacOS environment variable and failed to compile
=> chore: resolve Makefile error in MacOS

bindings/rust/Cargo.toml, bindings/rust/src/lib.rs
Fix compilation on Apple Silicon
change requirements to "^0.6"
=> chore: upgrade faster-hex to v0.6.0

Makefile, tools/compiler/Cargo.lock
When I tried to publish all crates, I found the `Cargo.lock` for compiler was not up-to-date.
So, this PR update that file and add a check in CI.
=> fix: `Cargo.lock` for compiler is not up-to-date

.github/workflows/ci.yaml, bindings/rust/Cargo.toml, examples/ci-tests/Cargo.toml, examples/tests-loader/Cargo.toml, examples/tests-loader/src/generators/rust.rs, examples/tests-utils-c/Cargo.toml, examples/tests-utils-rust/Cargo.toml, tools/codegen/Cargo.toml, tools/codegen/src/generator/languages/rust/properties.rs, tools/compiler/Cargo.lock, tools/compiler/Cargo.toml
Reader:
https://github.com/nervosnetwork/molecule/blob/706c5e0d61332cac545ce2184ef3d77dea23f990/tools/codegen/src/generator/languages/rust/reader/implementation.rs#L122-L125
Builder:
https://github.com/nervosnetwork/molecule/blob/706c5e0d61332cac545ce2184ef3d77dea23f990/tools/codegen/src/generator/languages/rust/builder/implementation.rs#L112-L114
=> fix: an API for partial read FixVec is incorrect

.github/workflows/ci.yaml, Makefile, bindings/rust/src/lib.rs
First, the code works fine with current stable rust toolchain.
But, rust toolchain doesn't guarantee that; so it could be broken in the future.
The latest docs said:
> Notice that the rules around uninitialized integers are not finalized yet, but until they are, it is advisable to avoid them.
And, there is no safe way to create an uninitialized array.
- At first, [`::std::mem::uninitialized()`] was the suggested method.
- One day, the compiler told us to replace that by [`MaybeUninit::uninit().assume_init()`].
But after read the docs carefully, we found that it said that it is advisable to avoid them because it could cause immediate undefined behavior in someday (when the rules around uninitialized integers are finalized).
- Now, there is no suitable API for that, so just remove the …
=> fix: remove a piece of unsafe code

examples/ci-tests/src/simple-example.rs, tools/codegen/src/generator/languages/rust/builder/setters.rs
case ref: https://github.com/nervosnetwork/axon/pull/68/files#diff-23e04433a8d944b64dc095f9c6ab49b7ebb452fb25fe461c0f31c7e02839f7eaR218-R229
The user needs to `replace` a value in the vector, and currently, the only way to do so is to iterate through the collection. With the `replace` interface, this large piece of code can be replaced
=> feat: add replace api to vector

.github/workflows/ci.yaml, bindings/rust/Cargo.toml, examples/ci-tests/Cargo.toml, examples/tests-loader/Cargo.toml, examples/tests-utils-c/Cargo.toml, examples/tests-utils-rust/Cargo.toml, tools/codegen/Cargo.toml, tools/codegen/src/generator/languages/c/mod.rs, tools/codegen/src/generator/languages/rust/builder/definition.rs, tools/codegen/src/generator/languages/rust/builder/setters.rs, tools/codegen/src/generator/languages/rust/import.rs, tools/compiler/Cargo.lock, tools/compiler/Cargo.toml
- chore: upgrade the default rust toolchain for the ci environment
- chore: bump version to v0.7.3
=> chore: bump version to v0.7.3

bindings/rust/src/bytes.rs, tools/codegen/src/generator/languages/rust/entity/mod.rs
`Bytes::from_static(..)` is a const function, we can use it in the default constructor for entities to improve the performance.
Ref: [`pub const fn from_static(bytes: &'static [u8]) -> Bytes`](https://docs.rs/bytes/1.1.0/bytes/struct.Bytes.html#method.from_static).
=> perf: use const functions as default constructors (only for `std`)

tools/codegen/src/generator/languages/rust/reader/implementation.rs
Close #60.
Since the removed code in the `else` branch of the following condition:
https://github.com/nervosnetwork/molecule/blob/5f94aa86d523d60e498ffefe01001fcf1ae70851/tools/codegen/src/generator/languages/rust/reader/implementation.rs#L180
then `Self::FIELD_COUNT` will be always greater than 0.
So this line of code could be removed.
=> fix: remove useless code: an always false condition

Makefile, tests/.gitignore, tests/Cargo.toml, tests/build.rs, tests/src/main.rs, tests/src/union_compatibility_test.rs, tests/union_foo_0_7_3.mol, tests/union_foo_with_custom_id.mol, tools/codegen/Cargo.toml, tools/codegen/src/ast/mod.rs, tools/codegen/src/ast/raw/mod.rs, tools/codegen/src/ast/raw/utils.rs, tools/codegen/src/ast/verified/complete.rs, tools/codegen/src/ast/verified/mod.rs, tools/codegen/src/ast/verified/recover.rs, tools/codegen/src/generator/languages/c/reader.rs, tools/codegen/src/generator/languages/rust/enumerator.rs, tools/codegen/src/generator/languages/rust/getters.rs, tools/codegen/src/generator/languages/rust/reader/implementation.rs, tools/codegen/src/grammar.pest, tools/codegen/src/ir/from_ast.rs, tools/codegen/src/ir/mod.rs, tools/codegen/src/parser/mod.rs, tools/codegen/src/utils.rs
This PR want to close #59 
working in progress.
=> [Feature] Add custom union ID syntax

bindings/rust/Cargo.toml, examples/ci-tests/Cargo.toml, examples/tests-loader/Cargo.toml, examples/tests-utils-c/Cargo.toml, examples/tests-utils-rust/Cargo.toml, tests/Cargo.toml, tools/codegen/Cargo.toml, tools/compiler/Cargo.lock, tools/compiler/Cargo.toml
We have merged "custom Union ID" feature (#65 ) into master, then this PR want to bump version from `0.7.3` to `v0.7.4`. @yangby-cryptape @quake
=> chore: bump version to v0.7.4

tools/codegen/src/ast/verified/default_content.rs
If there is a custom Union schema whose first item ID isn't `0`, the `default_content()` of `union` may be wrong value.
@yangby-cryptape @driftluo @code-monad
=> fix: union's default value should be first union item

examples/ci-tests/src/lib.rs, examples/tests-loader/src/generators/c.rs, test/schemas/types.mol, test/vectors/default.yaml, test/vectors/simple.yaml, tools/codegen/src/generator/languages/c/builder.rs
This PR:
- fix codegen for `C`'s default union value should be first union item.
- add test case for custom Union ID feature.
Request for review: @driftluo @yangby-cryptape @code-monad
=> add test case for custom Union ID feature

test/schemas/types.mol, test/vectors/default.yaml, test/vectors/simple.yaml, tools/codegen/src/generator/languages/c/builder.rs
This PR fix a bug in C code generator, and added some test case.
=> Fix: C code generator should provide `const uint8_t *` as 4th argument to  `mol_union_builder_initialize`

tools/codegen/src/generator/languages/rust/builder/definition.rs
Derive `Clone` trait can make batch construction smoother.
Before:
```rust
lazy_static {
pub ref TEMPLETE_SCRIPT: packed::Script = packed::ScriptBuilder::default().code_hash().hash_type().build();
}
let script_a = TEMPLETE_SCRIPT.clone().as_builder().args().build();
let script_b = TEMPLETE_SCRIPT.clone().as_builder().args().build();
```
After
```rust
lazy_static {
pub ref TEMPLETE_SCRIPT_BUILDEDR: packed::ScriptBuilder = packed::ScriptBuilder::default().code_hash().hash_type();
}
let script_a = TEMPLETE_SCRIPT_BUILDER.clone().args().build();
let script_b = TEMPLETE_SCRIPT_BUILDER.clone().args().build();
```
=> refactor(code_gen): derive Clone for *Builder

tools/codegen/src/ast/raw/utils.rs, tools/codegen/src/utils.rs
This fix the two compiler warnings remained on this project.
1. `warning: the borrowed expression implements the required traits`
2. `warning: the `Err`-variant returned from this function is very large`
=> chore: Fix compiler warning

Makefile, tools/codegen/src/ast/mod.rs, tools/codegen/src/ast/raw/mod.rs, tools/codegen/src/ast/raw/utils.rs, tools/codegen/src/ast/verified/complete.rs, tools/codegen/src/ast/verified/mod.rs, tools/codegen/src/ast/verified/recover.rs, tools/codegen/src/grammar.pest, tools/codegen/src/ir/from_ast.rs, tools/codegen/src/ir/mod.rs
This PR want to make molecule support syntax version identifier.
We can specify `syntax = {version}` now.
1. If syntax_version wasn't specified, it would be `1` by default.
2. All schema file you imported must have **same version** : a `syntax = 1` schema file can't import `syntax = 2` file, and `syntax = 2` file can't import `syntax = 1` schema file either.
--------
@yangby-cryptape @driftluo @code-monad @zhangsoledad Invite you to review this PR.
=> Add syntax_version identifier to molecule

examples/ci-tests/tests/build.rs, tools/codegen/src/generator/languages/rust/builder/implementation.rs, tools/codegen/src/generator/languages/rust/generator.rs
Implement more conversion traits to make entities easier to build/use (close #63):
* FooOpt from Foo
* FooArray from/into [Foo; n]
* FooArray TryFrom &[Foo]
* Union entity from item
* Vec FromIterator item
* ByteArray from/into [u8; n]
* ByteArray TryFrom &[u8]
* ByteArrayReader Into &[u8; n]
* ByteVec FromIterator u8
So instead of e.g.
```rust
.foo_opt(FooOpt::new_builder().set(Some(foo)).build())
.foo_vec(FooVec::new_builder().extend(foo_iter).build())
.foo_union(FooUnion::new_builder().set(foo).build())
```
we can use:
```rust
.foo_opt(foo.into())
.foo_vec(foo_iter.collect())
.foo_union(foo.into())
```
It's also easier to work with e.g. `Uint32`: `3u32.to_le_bytes().into()`, `u32::from_le_bytes(x.into())`.
=> feat: more conversion

docs/grammar/grammar.ebnf
sync with this update https://github.com/nervosnetwork/molecule/pull/65
=> add custom union id in ebnf definition

bindings/rust/Cargo.toml, bindings/rust/src/bytes.rs, bindings/rust/src/lib.rs, tools/compiler/Cargo.lock
https://github.com/nervosnetwork/molecule/pull/75 introduced bytes crate in no_std env, which requires ckb2023 hardfork edition or [modification](https://github.com/xxuejie/ckb-contract-bytes-without-a) on old contract projects.
This PR add a `bytes_vec` feature, make it easier to upgrading older projects that want to continue using vec:
```diff
- molecule = { version = "0.7.5", default-features = false }
+ molecule = { version = "0.8.0", default-features = false, features = ["bytes_vec"] }
```
=> feat: add bytes_vec features

bindings/rust/src/bytes.rs
=> Derive Ord for bytes::Bytes

README.md
Instructions for adding features, and how to properly specify features in ckb scripts.
https://github.com/nervosnetwork/molecule/issues/94
=> doc: add features description
